### ISSUE TITLE
Update in the summarizer to use IndicBART finetuned model

### ISSUE THREAD

**Issue by ratishsp** [d0r1h/SAR#1]
Hi Pawan, 
Nice work in building the summarizer! 
I am one of the developers behind IndicBART. I noticed that you use the IndicBART model as-is in https://huggingface.co/spaces/d0r1h/Hindi_News_Summarizer/blob/main/summarizer.py. However, IndicBART is a pretrained model which needs to be finetuned for summarization. We have released an IndicBART model finetuned on Indic languages of XLSum at https://huggingface.co/ai4bharat/IndicBART-XLSum. It will be great if you can make use of this model in your summarizer.

**Comment by d0r1h** [comment]
First, thank you for **IndicBART**. 

Yes, I am kind of doing benchmarking, so as a base model I have used pre-trained(IndicBart), and also I'll be using fine-tuned version on XLSum in this project. 

Thank you.
